export const WORKSPACE_OVERVIEW_UI_COPY = {
	activeProjects: "Active Projects",
	addLiveBlock: "Add live block",
	any: "Any",
	archived: "Archived",
	areas: "Areas",
	attentionRequired: "Attention Required",
	columns: "Columns",
	grouping: "Grouping",
	hide: "Hide",
	lastReportedHealth: "Last reported health",
	lifecycle: "Lifecycle",
	listName: "Name",
	loading: "Loading…",
	membershipFromConditions: "Membership comes from list conditions.",
	moveDown: "Move down",
	moveUp: "Move up",
	newList: "New list",
	none: "None",
	notArchived: "Not archived",
	openSourceRecord: "Open source record",
	recentWork: "Recent Work",
	remove: "Remove",
	savedLists: "Saved lists",
	saveList: "Save list",
	show: "Show",
	sort: "Sort",
	sortAsc: "A–Z",
	sortDesc: "Z–A",
	stage: "Stage",
	targetDate: "Target date",
	unavailable: "Workspace overview is unavailable.",
	upcoming: "Upcoming",
	workspace: "Workspace",
} as const;
