export const MOODBOARDS_COPY = {
	addVisual: "Add visual",
	caption: "Caption",
	collapseGroup: "Collapse",
	createMoodboard: "Create Moodboard",
	expandGroup: "Expand",
	externalLink: "External link",
	fileAttachment: "File Attachment",
	fitView: "Fit View",
	group: "Group",
	inspect: "Inspect",
	moodboard: "Moodboard",
	moveDown: "Move down",
	moveUp: "Move up",
	noMoodboards: "No Moodboards yet.",
	openSourceRecord: "Open Source Record",
	outline: "Outline",
	title: "Title",
} as const;
