export const MOODBOARDS_COPY = {
	addColorSwatch: "Add Color Swatch",
	addPaletteGroup: "Add palette group",
	addVisual: "Add visual",
	caption: "Caption",
	collapseGroup: "Collapse",
	colorSwatch: "Color Swatch",
	createMoodboard: "Create Moodboard",
	crop: "Crop",
	exitPresentationMode: "Exit Presentation Mode",
	expandGroup: "Expand",
	externalLink: "External link",
	eyedrop: "Eyedrop",
	fileAttachment: "File Attachment",
	fitView: "Fit View",
	focusOrder: "Focus order",
	group: "Group",
	hex: "HEX",
	hsl: "HSL",
	inspect: "Inspect",
	moodboard: "Moodboard",
	moveDown: "Move down",
	moveUp: "Move up",
	noLiveSourceLinks: "Output carries no live source links.",
	noMoodboards: "No Moodboards yet.",
	note: "Note",
	openSourceRecord: "Open Source Record",
	outline: "Outline",
	paletteGroup: "Palette group",
	pdf: "PDF",
	picker: "Picker",
	png: "PNG",
	presentationMode: "Presentation Mode",
	preview: "Preview",
	rgb: "RGB",
	rotate: "Rotate 90°",
	snapshot: "Snapshot",
	title: "Title",
} as const;
