export const MOODBOARDS_COPY = {
	addVisual: "Add visual",
	caption: "Caption",
	collapseGroup: "Collapse",
	createMoodboard: "Create Moodboard",
	crop: "Crop",
	exitPresentationMode: "Exit Presentation Mode",
	expandGroup: "Expand",
	externalLink: "External link",
	fileAttachment: "File Attachment",
	fitView: "Fit View",
	focusOrder: "Focus order",
	group: "Group",
	inspect: "Inspect",
	moodboard: "Moodboard",
	moveDown: "Move down",
	moveUp: "Move up",
	noLiveSourceLinks: "Output carries no live source links.",
	noMoodboards: "No Moodboards yet.",
	openSourceRecord: "Open Source Record",
	outline: "Outline",
	pdf: "PDF",
	png: "PNG",
	presentationMode: "Presentation Mode",
	preview: "Preview",
	rotate: "Rotate 90°",
	snapshot: "Snapshot",
	title: "Title",
} as const;
