export const EXTERNAL_HANDOFFS_COPY = {
	addSelectedVersion: "Add selected version",
	body: "Body",
	constraints: "Constraints",
	executor: "Executor",
	expectedOutput: "Expected output",
	externalExecutionHandoff: "External Execution Handoff",
	github: "GitHub",
	handoff: "Handoff",
	includeThisWork: "Include this Work",
	kind: "Kind",
	open: "Open",
	producedAt: "Produced at",
	purpose: "Purpose",
	recordId: "Record",
	selectedVersions: "Selected versions",
	sourceOfTruth: "Source of truth is in the app",
	startHandoff: "Start Handoff",
	title: "Title",
	versionId: "Version",
} as const;

export const SELECTED_VERSION_KINDS = [
	"Work",
	"Document",
	"Decision",
	"Risk",
	"Open Question",
	"Source",
] as const;
