export const DAILY_FOCUS_COPY = {
	accept: "Accept",
	add: "Add",
	candidates: "Candidates",
	candidatesEmpty: "No Candidates for this day.",
	dailyFocus: "Daily Focus",
	empty: "No Work in Daily Focus for this day.",
	loading: "Loading…",
	reappearDateArrived: "Reappear date has arrived",
	reject: "Reject",
	remove: "Remove",
	selectedDay: "Selected day",
	targetDateNear: "Target date is near",
	work: "Work",
} as const;
