export const FEEDBACK_COPY = {
	archived: "Archived",
	attachments: "Attachments",
	channel: "Channel",
	company: "Company",
	contact: "Contact",
	convertToWork: "Convert to Work",
	createFeedback: "Create Feedback",
	createFromSource: "Create from Source",
	decision: "Decision",
	description: "Description",
	feed: "Feed",
	feedback: "Feedback",
	link: "Link",
	new: "New",
	noFeed: "No Feed records yet.",
	noFeedback: "No Feedback yet.",
	occurredAt: "Occurred at",
	openSourceRecord: "Open Source Record",
	origin: "Origin",
	originalMessage: "Original message",
	project: "Project",
	reviewed: "Reviewed",
	source: "Source",
	status: "Status",
	title: "Title",
	work: "Work",
} as const;

export const FEEDBACK_STATUSES = [
	FEEDBACK_COPY.new,
	FEEDBACK_COPY.reviewed,
	FEEDBACK_COPY.archived,
] as const;
