export const DECISIONS_COPY = {
	allDecisions: "All Decisions",
	confirm: "Confirm",
	confirmSupersession: "Confirm supersession",
	createDecision: "Create Decision",
	decision: "Decision",
	decisionText: "Decision text",
	evidence: "Evidence",
	livesChanging: "Lives that will change",
	noDecisions: "No Decisions yet.",
	openCurrentDecision: "Open current decision",
	preview: "Preview",
	rationale: "Rationale",
	removeSupersession: "Remove supersession",
	supersedeAnotherDecision: "Supersede another decision",
	superseded: "Superseded",
	supersedes: "Supersedes",
	title: "Title",
	transitionRationale: "Transition rationale",
	valid: "Valid",
	withdraw: "Withdraw",
	withdrawn: "Withdrawn",
} as const;
