export const CONTACT_AND_COMPANY_COPY = {
	belongsToCompany: "Belongs to Company",
	company: "Company",
	contact: "Contact",
	createCompany: "Create Company",
	createContact: "Create Contact",
	displayName: "Display name",
	duplicateCandidates: "Duplicate candidates",
	email: "Email",
	emailAliases: "Email aliases",
	feedbackHistory: "Feedback history",
	fieldConflicts: "Field conflicts",
	mergeContacts: "Merge Contacts",
	mergePreview: "Merge Preview",
	name: "Name",
	noCompanies: "No Companies yet.",
	noContacts: "No Contacts yet.",
	noDuplicateCandidates: "No duplicate candidates.",
	none: "None",
	openSourceRecord: "Open Source Record",
	origin: "Origin",
	personaRelations: "Persona",
	relationsToRewrite: "Relations",
	strongCopyCandidate: "Strong copy candidate",
	survivingRecord: "Surviving record",
	weakSuggestion: "Weak suggestion",
} as const;
