export const CONTACT_AND_COMPANY_COPY = {
	belongsToCompany: "Belongs to Company",
	company: "Company",
	contact: "Contact",
	createCompany: "Create Company",
	createContact: "Create Contact",
	displayName: "Display name",
	duplicateCandidates: "Duplicate candidates",
	email: "Email",
	name: "Name",
	noCompanies: "No Companies yet.",
	noContacts: "No Contacts yet.",
	noDuplicateCandidates: "No duplicate candidates.",
	none: "None",
	openSourceRecord: "Open Source Record",
	strongCopyCandidate: "Strong copy candidate",
	weakSuggestion: "Weak suggestion",
} as const;
