export const USER_FLOW_COPY = {
	action: "Action",
	align: "Align",
	archived: "Archived",
	bindScreen: "Bind Screen",
	collapseGroup: "Collapse",
	condition: "Condition",
	createScreen: "Create Screen",
	createUserFlow: "Create User Flow",
	decision: "Decision",
	description: "Description",
	expandGroup: "Expand",
	fitView: "Fit View",
	group: "Group",
	inspect: "Inspect",
	moveDown: "Move down",
	moveUp: "Move up",
	noUserFlows: "No User Flows yet.",
	openSourceRecord: "Open Source Record",
	outline: "Outline",
	placeNode: "Place node",
	screen: "Screen",
	section: "Section",
	stateOutcome: "State/Outcome",
	title: "Title",
	transition: "Transition",
	unbind: "Unbind",
	undo: "Undo",
	userFlow: "User Flow",
} as const;

export const FLOW_NODE_KINDS = [
	USER_FLOW_COPY.screen,
	USER_FLOW_COPY.action,
	USER_FLOW_COPY.decision,
	USER_FLOW_COPY.stateOutcome,
	USER_FLOW_COPY.section,
] as const;
