export const FOCUS_PERIOD_COPY = {
	active: "Active",
	add: "Add",
	alreadyInAnActivePeriod:
		"Work is already in an active Focus Period. Use Move.",
	cancel: "Cancel",
	canceled: "Canceled",
	close: "Close",
	closed: "Closed",
	create: "Create Focus Period",
	empty: "No Focus Period yet.",
	endDate: "End date",
	focusPeriod: "Focus Period",
	loading: "Loading…",
	members: "Work",
	move: "Move",
	planned: "Planned",
	purpose: "Purpose",
	purposeRequired: "Purpose is required.",
	remove: "Remove",
	startDate: "Start date",
	stillOpenWork: "Still-open Work",
	windowMustBeOneToEightWeeks: "Focus Period must be 1–8 weeks.",
	work: "Work",
} as const;
