export const FOCUS_PERIOD_COPY = {
	active: "Active",
	add: "Add",
	blockedBy: "Blocked by",
	blocks: "Blocks",
	cancel: "Cancel",
	canceled: "Canceled",
	close: "Close",
	closed: "Closed",
	create: "Create Focus Period",
	cycle: "These records wait on each other.",
	dependencies: "Dependencies",
	empty: "No Focus Period yet.",
	endDate: "End date",
	focusPeriod: "Focus Period",
	loading: "Loading…",
	members: "Work",
	openSourceRecord: "Open source record",
	planned: "Planned",
	purpose: "Purpose",
	purposeRequired: "Purpose is required.",
	remove: "Remove",
	resolved: "Resolved",
	startDate: "Start date",
	stillOpenWork: "Still-open Work",
	windowMustBeOneToEightWeeks: "Focus Period must be 1–8 weeks.",
	work: "Work",
} as const;
