export const SOURCES_COPY = {
	accessedAt: "Accessed at",
	address: "Address",
	approvedVersion: "Approved version",
	capturedContent: "Captured content",
	createSource: "Create Source",
	excerpt: "Excerpt",
	externalId: "External id",
	externalRecordType: "External record type",
	historicalSnapshot: "Historical snapshot",
	keepCurrentVersion: "Keep current version",
	liveExternalSource: "Live external source",
	livePreview: "Live preview",
	loadPlayer: "Load player",
	newerSourceVersionExists: "Newer Source version exists",
	noMatchInCandidateVersion: "No match in candidate version",
	noSources: "No Sources yet.",
	provider: "Provider",
	rebindToNewVersion: "Rebind to new version",
	recheckSource: "Recheck source",
	reviewedKeepCurrentVersion: "Reviewed; keep current version",
	saveAsNewSourceVersion: "Save as new Source version",
	saveAsSource: "Save as Source",
	showAddress: "Show address",
	showDescription: "Show description",
	showImage: "Show image",
	source: "Source",
	sourceCheck: "Source Check",
	thirdPartyFetchWillOccur: "A third-party server will be contacted.",
	thirdPartyWarning: "This loads third-party YouTube content.",
	title: "Title",
	versions: "Versions",
	youtubeUnavailable: "This video cannot be shown.",
} as const;
