export const SOURCES_COPY = {
	accessedAt: "Accessed at",
	address: "Address",
	approvedVersion: "Approved version",
	capturedContent: "Captured content",
	createSource: "Create Source",
	excerpt: "Excerpt",
	externalId: "External id",
	externalRecordType: "External record type",
	historicalSnapshot: "Historical snapshot",
	liveExternalSource: "Live external source",
	livePreview: "Live preview",
	loadPlayer: "Load player",
	noSources: "No Sources yet.",
	provider: "Provider",
	saveAsNewSourceVersion: "Save as new Source version",
	saveAsSource: "Save as Source",
	showAddress: "Show address",
	showDescription: "Show description",
	showImage: "Show image",
	source: "Source",
	thirdPartyWarning: "This loads third-party YouTube content.",
	title: "Title",
	versions: "Versions",
	youtubeUnavailable: "This video cannot be shown.",
} as const;
