export const RETURN_TO_WORK_COPY = {
	closeTour: "Close tour",
	empty: "No Return to Work cards from current records.",
	lastUpdated: "Last updated",
	longInTheSameStatus: "Long in the same status",
	nextConcreteStep: "Next concrete step",
	openRemainderInTheList: "Open remainder in the list",
	openSourceRecord: "Open source record",
	returnToWork: "Return to Work",
	save: "Save",
	sinceYouLastLooked: "Since you last looked",
	skip: "Skip",
	tourShowsFirstVisualChanges: "Tour shows the first 12 visual changes.",
	tourTheVisualChanges: "Tour the visual changes",
} as const;
