export const RECORD_DISCOVERY_COPY = {
	applyPaste: "Apply paste",
	archived: "Archived",
	assumption: "Assumption",
	captureInboxItem: "Capture Inbox item",
	company: "Company",
	contact: "Contact",
	decision: "Decision",
	document: "Document",
	draft: "Draft",
	emptyQuery: "Type to search authorized records.",
	excludeFromApply: "Exclude from apply",
	externalSurface: "External Surface",
	feedback: "Feedback",
	fileAttachment: "File Attachment",
	filter: "Filter",
	githubExternalRecord: "GitHub external record",
	includeArchived: "Include archived",
	linkPassword: "Link password",
	matches: "matches",
	milestone: "Milestone",
	moodboard: "Moodboard",
	noMatches: "No matching records.",
	openQuestion: "Open Question",
	openSourceRecord: "Open source record",
	pasteNotApplied: "Paste did not apply; no rows were written.",
	personalWiki: "Personal Wiki",
	plannedTestCase: "Planned Test Case",
	previewPaste: "Preview paste",
	productGap: "Product Gap",
	productionIncident: "Production Incident",
	project: "Project",
	projectGoal: "Project Goal",
	projectRelease: "Project Release",
	projectWall: "Project Wall",
	query: "Query",
	risk: "Risk",
	saveAsSmartCollection: "Save as Smart Collection",
	saveDoesNotStoreMembership:
		"Save as Smart Collection does not store membership here.",
	screen: "Screen",
	search: "Search",
	secret: "Secret",
	sessionTests: "Session Tests",
	shareToken: "Share token",
	sort: "Sort",
	source: "Source",
	table: "Table",
	tableUnavailable: "Table is not available for this type.",
	technicalDiagram: "Technical Diagram",
	testAssessment: "Test assessment",
	testGap: "Test Gap",
	testHandoff: "Test Handoff",
	testSession: "Test Session",
	type: "Type",
	unavailable: "Search is unavailable.",
	userFlow: "User Flow",
	userResearchSession: "User Research Session",
	wikiDocument: "Wiki Document",
	work: "Work",
} as const;
