export const RECORD_DISCOVERY_COPY = {
	allDecisions: "All Decisions",
	allDesigns: "All Designs",
	allDocuments: "All Documents",
	allFiles: "All Files",
	allProjectReleases: "All Project Releases",
	allResearchSessions: "All Research Sessions",
	allRisks: "All Risks",
	allSources: "All Sources",
	allTechnicalDiagrams: "All Technical Diagrams",
	allTests: "All Tests",
	allWork: "All Work",
	anyScope: "Any",
	archived: "Archived",
	dataModel: "Data Model",
	decision: "Decision",
	diagramAuthorityMode: "Diagram Authority Mode",
	document: "Document",
	emptyIndex: "No records in this index.",
	emptyQuery: "Type to search authorized records.",
	externalSourceLink: "External Source Link",
	fileAttachment: "File Attachment",
	folder: "Folder",
	importedIndependentCopy: "Imported Independent Copy",
	includeArchived: "Include archived",
	matches: "matches",
	metadata: "Metadata",
	moodboard: "Moodboard",
	noMatches: "No matching records.",
	openSourceRecord: "Open source record",
	persona: "Persona",
	personalWiki: "Personal Wiki",
	plannedTestCase: "Planned Test Case",
	productAuthoredModel: "Product-authored Model",
	project: "Project",
	projectRelease: "Project Release",
	projectWall: "Project Wall",
	query: "Query",
	recordType: "Type",
	repositoryDerivedView: "Repository-derived View",
	researchSession: "Research Session",
	risk: "Risk",
	scope: "Scope",
	screen: "Screen",
	search: "Search",
	sessionTest: "Session Test",
	source: "Source",
	technicalArchitecture: "Technical Architecture",
	technicalSequence: "Technical Sequence",
	testAssessment: "Test assessment",
	testGap: "Test Gap",
	testHandoff: "Test Handoff",
	testSession: "Test Session",
	unavailable: "Search is unavailable.",
	userFlow: "User Flow",
	work: "Work",
} as const;
