export const SCREENS_COPY = {
	active: "Active",
	align: "Align",
	archive: "Archive",
	archived: "Archived",
	broken: "Broken",
	button: "Button",
	card: "Card",
	chart: "Chart",
	collapseGroup: "Collapse",
	createScreen: "Create Screen",
	deletePermanently: "Permanently Delete",
	detachLink: "Detach Link",
	expandGroup: "Expand",
	fitView: "Fit View",
	group: "Group",
	includeArchived: "Include archived",
	input: "Input",
	inspect: "Inspect",
	inTrash: "In Trash",
	liveSource: "Live source",
	moveDown: "Move down",
	moveToTrash: "Move to Trash",
	moveUp: "Move up",
	navigation: "Navigation",
	noScreens: "No Screens yet.",
	noScreensInTrash: "No Screens in Trash.",
	openSourceRecord: "Open Source Record",
	outline: "Outline",
	restore: "Restore",
	screen: "Screen",
	table: "Table",
	text: "Text",
	title: "Title",
	titleRequired: "Title is required.",
	unarchive: "Unarchive",
	unavailable: "Screen could not be created.",
	wireframe: "Wireframe",
} as const;
