export const RECORD_DISCOVERY_COPY = {
	allDecisions: "All Decisions",
	allDesigns: "All Designs",
	allDocuments: "All Documents",
	allFiles: "All Files",
	allProjectReleases: "All Project Releases",
	allResearchSessions: "All Research Sessions",
	allRisks: "All Risks",
	allSources: "All Sources",
	allTechnicalDiagrams: "All Technical Diagrams",
	allTests: "All Tests",
	allWork: "All Work",
	anyScope: "Any",
	applyPaste: "Apply paste",
	archived: "Archived",
	assumption: "Assumption",
	captureInboxItem: "Capture Inbox item",
	company: "Company",
	contact: "Contact",
	dataModel: "Data Model",
	decision: "Decision",
	diagramAuthorityMode: "Diagram Authority Mode",
	document: "Document",
	draft: "Draft",
	emptyIndex: "No records in this index.",
	emptyQuery: "Type to search authorized records.",
	excludeFromApply: "Exclude from apply",
	externalSourceLink: "External Source Link",
	externalSurface: "External Surface",
	feedback: "Feedback",
	fileAttachment: "File Attachment",
	filter: "Filter",
	folder: "Folder",
	githubExternalRecord: "GitHub external record",
	importedIndependentCopy: "Imported Independent Copy",
	includeArchived: "Include archived",
	linkPassword: "Link password",
	matches: "matches",
	metadata: "Metadata",
	milestone: "Milestone",
	moodboard: "Moodboard",
	noMatches: "No matching records.",
	openFullPage: "Open full page",
	openQuestion: "Open Question",
	openSourceRecord: "Open source record",
	pasteNotApplied: "Paste did not apply; no rows were written.",
	persona: "Persona",
	personalWiki: "Personal Wiki",
	plannedTestCase: "Planned Test Case",
	previewPaste: "Preview paste",
	productAuthoredModel: "Product-authored Model",
	productGap: "Product Gap",
	productionIncident: "Production Incident",
	project: "Project",
	projectGoal: "Project Goal",
	projectRelease: "Project Release",
	projectWall: "Project Wall",
	query: "Query",
	recordType: "Type",
	repositoryDerivedView: "Repository-derived View",
	researchSession: "Research Session",
	risk: "Risk",
	saveAsSmartCollection: "Save as Smart Collection",
	saveDoesNotStoreMembership:
		"Save as Smart Collection does not store membership here.",
	scope: "Scope",
	screen: "Screen",
	search: "Search",
	secret: "Secret",
	sessionTest: "Session Test",
	sessionTests: "Session Tests",
	shareToken: "Share token",
	sort: "Sort",
	source: "Source",
	table: "Table",
	tableUnavailable: "Table is not available for this type.",
	technicalArchitecture: "Technical Architecture",
	technicalDiagram: "Technical Diagram",
	technicalSequence: "Technical Sequence",
	testAssessment: "Test assessment",
	testGap: "Test Gap",
	testHandoff: "Test Handoff",
	testSession: "Test Session",
	type: "Type",
	unavailable: "Search is unavailable.",
	userFlow: "User Flow",
	userResearchSession: "User Research Session",
	wikiDocument: "Wiki Document",
	work: "Work",
} as const;
