export const RECORD_DISCOVERY_COPY = {
	archived: "Archived",
	captureInboxItem: "Capture Inbox item",
	document: "Document",
	draft: "Draft",
	emptyQuery: "Type to search authorized records.",
	externalSurface: "External Surface",
	fileAttachment: "File Attachment",
	githubExternalRecord: "GitHub external record",
	includeArchived: "Include archived",
	linkPassword: "Link password",
	matches: "matches",
	noMatches: "No matching records.",
	openFullPage: "Open full page",
	openSourceRecord: "Open source record",
	personalWiki: "Personal Wiki",
	project: "Project",
	query: "Query",
	search: "Search",
	secret: "Secret",
	shareToken: "Share token",
	technicalDiagram: "Technical Diagram",
	unavailable: "Search is unavailable.",
	work: "Work",
} as const;
